// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InjectSampleMudBlazor
{
    internal sealed partial class Vsix
    {
        public const string Id = "InjectSampleMudBlazor.46537894-1bd9-4c96-b8bf-4be0c6e85c3b";
        public const string Name = "InjectSampleMudBlazor";
        public const string Description = @"Inject sample code of components to current documentI";
        public const string Language = "en-US";
        public const string Version = "0.0.3";
        public const string Author = "Bar San";
        public const string Tags = "MudBlazor Blazor Component extentions";
    }
}
