// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InjectSampleMudBlazor
{
    internal sealed partial class Vsix
    {
        public const string Id = "InjectSampleMudBlazor.46537894-1bd9-4c96-b8bf-4be0c6e85c3b";
        public const string Name = "InjectSampleMudBlazor";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "בר סנני";
        public const string Tags = "";
    }
}
