using Core.Models;
using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace Core.Services
{
    public class MISDocumentTextService 
    {
        private string[] sectionBreaks = new string[2] { "<", "@code" };
        private StringBuilder _stringBuilder = new StringBuilder();
        
        public async Task OrginazeTextInputAsync(string text, MISTextOrginaize sectionOrginaize)
        {
            _stringBuilder.Clear();
            var sections = GenerateSectionsFromDocument();

            // Read string line by line
            StringReader reader = new StringReader(text);

            // Keep track of current section
            int currentSection = 0;
            int sectionsLinesAdded = 0;
            
            // hold current line
            string line;

            while (!((line = await reader.ReadLineAsync()) is null))
            {
                sectionsLinesAdded++;

                // Html section
                if (currentSection != 1 && line.StartsWith(sectionBreaks[0]))
                {
                    sectionOrginaize.UsingsSection.LinesAddedToSection = sectionsLinesAdded--;
                    SectionUpdated(ref sections, ref currentSection);
                    sectionsLinesAdded = 0;
                }

                // C# section
                if (currentSection != 2 && line.StartsWith(sectionBreaks[1]))
                {
                    sectionOrginaize.HtmlSection.LinesAddedToSection = sectionsLinesAdded--;
                    SectionUpdated(ref sections, ref currentSection);
                    sectionsLinesAdded = 0;
                }
                
                 _stringBuilder.AppendLine(line);
            }

            // Added c# code to code section
            sections[2] += _stringBuilder.ToString();
            sectionOrginaize.CodeSection.LinesAddedToSection = sectionsLinesAdded--;

            // Dispose reader
            reader.Dispose();

            sectionOrginaize.TextSections = sections;
        }

        /// <summary>
        /// Get current document text in visual studio and divade to sections and addetion data to perform the injection <br/>
        /// Using (CSharp + Blazor section) <br/>
        /// Html (Razor section) <br/>
        /// Code (CSharp section) <br/>
        /// </summary>
        /// <param name="text">Current text in the document</param>
        /// <returns>New <see cref="MISTextOrginaize"/> object</returns>
        public async Task<MISTextOrginaize> TextSectionDivderAsync(string text)
        {
            // Read string line by line
            StringReader reader = new StringReader(text);

            // Keep track of current section and offsets
            int currentSection = 0;
            int[] offsets = new int[2];
            int currentLineNum = 0;

            // hold current line
            string line;

            while (!((line = await reader.ReadLineAsync()) is null))
            {
                currentLineNum++;

                // Html section
                if (currentSection != 1 && line.StartsWith(sectionBreaks[0]))
                    offsets[0] = currentLineNum;

                // C# section
                if (currentSection != 2 && line.StartsWith(sectionBreaks[1]))
                    offsets[1] = currentLineNum;
            }

            // Dispose reader
            reader.Dispose();

            return new MISTextOrginaize(0, offsets[0], offsets[1]);
        }



        private void SectionUpdated(ref string[] sections, ref int currentSection)
        {
            sections[currentSection++] += _stringBuilder.ToString();
            _stringBuilder.Clear();
        }


        private string[] GenerateSectionsFromDocument()
            =>  new string[3]
            {
                "",
                $"\n<!--{Constants.AutoGenerated_Comment}-->\n",
                $"\n/*{Constants.AutoGenerated_Comment}*/\n"
            };
    }
}
